# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12xW21JTM_rtJ25YP4fJRzp2zXSg-37-z
"""

root@nandini-desktop:/jetson-inference/data/cracksapp# cat cracksfinal.py
import streamlit as st
from ultralytics import YOLO
import os
import shutil


# Setup folders
UPLOAD_DIR = "uploads"
OUTPUT_DIR = "outputs"

os.makedirs(UPLOAD_DIR, exist_ok=True)
os.makedirs(OUTPUT_DIR, exist_ok=True)


# Streamlit UI
st.set_page_config(page_title="Crack Detection", layout="centered")
st.title("🛠 Crack Detection App (YOLOv8)")

st.write("Upload an image or video to detect cracks.")


# Load YOLO model
@st.cache_resource
def load_model():
    return YOLO("modelweights/best.pt")

model = load_model()


# File uploader
uploaded_file = st.file_uploader(
    "Upload Image or Video",
    type=["jpg", "jpeg", "png", "mp4", "avi"]
)

# Process file
if uploaded_file is not None:

    # Save uploaded file
    input_path = os.path.join(UPLOAD_DIR, uploaded_file.name)
    with open(input_path, "wb") as f:
        f.write(uploaded_file.getbuffer())

    st.success(f"File uploaded: {uploaded_file.name}")

    # Run inference
    results = model(input_path)


    # IMAGE CASE
    if uploaded_file.name.lower().endswith((".jpg", ".jpeg", ".png")):

        output_path = os.path.join(OUTPUT_DIR, f"out_{uploaded_file.name}")

        # Save annotated image
        results[0].save(output_path)

        # Show image
        st.image(output_path, caption="Detected Cracks", use_column_width=True)

        # Crack count
        crack_count = len(results[0].boxes)
        st.markdown(f"### 🔍 Cracks detected: **{crack_count}**")

        # Download button
        with open(output_path, "rb") as f:
            st.download_button(
                label="⬇️ Download Annotated Image",
                data=f,
                file_name=f"out_{uploaded_file.name}",
                mime="image/jpeg"
            )


    # VIDEO CASE
    else:
        st.info("Processing video… this may take some time ⏳")

        # YOLO automatically saves video in runs/
        results = model(
            input_path,
            save=True,
            project=OUTPUT_DIR,
            name="video_results",
            exist_ok=True
        )

        # Find saved video
        saved_dir = os.path.join(OUTPUT_DIR, "video_results")
        video_files = [f for f in os.listdir(saved_dir) if f.endswith((".mp4", ".avi"))]

        if video_files:
            video_path = os.path.join(saved_dir, video_files[0])
            st.video(video_path)

            with open(video_path, "rb") as f:
                st.download_button(
                    label="⬇️ Download Annotated Video",
                    data=f,
                    file_name=video_files[0],
                    mime="video/mp4"
                )
        else:
            st.error("Annotated video not found.")
